.TH TEXTGRAPH 1 2024-06-08
.SH name
TextGraph \- Text graphing utility
.SH SYNOPSIS
.B textgraph [OPTIONS] [\fIinput_file\fB]

.SH DESCRIPTION
.B textgraph
TermGraph is a utility for graphing

.SH OPTIONS
.IP "\fB--help\fR"
Display help information.

.IP "\fB-s, --silent\fR"
Disable distracting elements, such as axis and non-graph text.

.IP "\fB-n, --last-n\fR \fIcount\fR"
If specified, only the newest \fIcount\fR samples will be plotted.
This can be useful if you want to follow the latest state of a graph that is piped in.

.IP "\fB-c, --cut\fR"
This is a special case of \fB--last-n\fR. Where the number of columns 
\fB--width\fI will be used for the count.

.IP "\fB-a, --ascii\fR"
Shorthand for -t ascii, if multiple options setting mode is specified, 
the last will likely be respected.

.IP "\fB-b, --braille\fR"
Shorthand for -t braille, if multiple options setting mode is specified, 
the last will likely be respected.

.IP "\fB-t\fR \fIstar\fR|\fIascii\fR|\fIbraille\fR|\fIbraille6\fR|\fIbraille8\fR"
The type of graph to draw,
it defaults to \fBstar\fR, which is the fastest one.

\fBstar\fR
Scatter plot using only the '*' character.

\fBascii\fR 
Ascii is slightly prettier to look at.

\fBbraille\fR,
\fBbraille6\fR
Uses braille characters to draw higher resolution plots.

\fBbraille8\fR
This is the most scatter-plot-ish with the highest resolution, but also the most buggy.

.IP "\fB-w, --width\fR \fIwidth\fR"
Specify a width for the output. 
If not specified, it will attempt to determine the TTY width and use that.
If it cannot be automatically determined, it will fail.

.IP "\fB-h, --height\fR \fIheight\fR"
Specify a height for the output. 
If not specified, it will attempt to determine the TTY height and use that.
If it cannot be automatically determined, it will fail.

.IP "\fB--color\fR \fIyes\fR|\fIno\fR"
Enable or disable colors, by default color will be enabled if it looks like a tty is connected.

It can therefore be nice to use \fB--color yes\fR
if you are piping the output into another program that supports colors.

.SH EXAMPLES

The simplest version is if you have a text file of values
.PP
.nf
.RS
cat \fIfile\fR | textgraph
.RE
.fi
.PP

