# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
# cargo2rpm does return 1 for the crate, but we don't care about the libraries
# for this rpm
%global __cargo_is_lib() 0

%global crate textgraph

%define cargo_config .cargo/config

Name:           textgraph
Version:        %{package_version}
Release:        %{package_release}
Summary:        Text graphing utility

#License:        GPLv3
Source:        	%{name}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24

%description
Text graphing utility

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
# This is not best practice, but it was somewhat annoying to actually get all
# dependencies vendored/packaged properly.
# currently this app doesn't have any cargo dependencies, but keeping it for reference
#sed -i '/^\[source\.crates-io\]/,/^$/d' %{cargo_config}
#sed -i '/^\[source\.local-registry\]/,/^$/d' %{cargo_config}
#sed -i '/^\[net\]/,/^$/d' %{cargo_config}
#echo "[net]" >> %{cargo_config}
#echo "git-fetch-with-cli = true" >> %{cargo_config}
%cargo_build

%install
%cargo_install

mkdir -p %{buildroot}%{_mandir}/man1
install tg.1 %{buildroot}%{_mandir}/man1/tg.1

%if %{with check}
%check
%cargo_test
%endif

%files
%doc README.md
%{_bindir}/tg
%{_mandir}/man1/tg.1.gz

%changelog
%autochangelog
