# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
# cargo2rpm does return 1 for the crate, but we don't care about the libraries
# for this rpm
%global __cargo_is_lib() 0

%global crate textgraph

%define cargo_config .cargo/config

Name:           textgraph
Version:        %{package_version}
Release:        %{package_release}
Summary:        Text graphing utility

License:        GPLv3
Source:        	%{name}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  rust-libc-devel

%description
Text graphing utility

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

mkdir -p %{buildroot}%{_mandir}/man1
install textgraph.1 %{buildroot}%{_mandir}/man1/textgraph.1

%if %{with check}
%check
%cargo_test
%endif

%files
%doc README.md
%{_bindir}/textgraph
%{_mandir}/man1/textgraph.1.gz

%changelog
%autochangelog
